services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "sqlite:///data/sqlite.db"

  sqlite:
    image: hibitdev/sqlite:latest
    container_name: sqlite
    hostname: sqlite.hibit
    ports:
      - "8191:8191"
    volumes:
      - ./sqlite:/db
    command: [ "tail", "-f", "/dev/null" ]

volumes:
  sqlite-data: